service: social_simulation
image: your-user/social_simulation

servers:
  web:
    - 192.168.0.1

proxy:
  ssl: true
  host: app.example.com

registry:
  username: your-user
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    # Configuración simplificada para SQLite
    RAILS_SERVE_STATIC_FILES: true
    DATABASE_URL: sqlite3:/rails/db/production.sqlite3

volumes:
  - "social_simulation_data:/rails/db"  # Para persistencia de SQLite
  - "social_simulation_storage:/rails/storage"  # Active Storage

asset_path: /rails/public/assets

builder:
  arch: amd64